# basic options
title: Ryan Bae
author: Ryan Bae
email: ryanbae89@gmail.com
email2: rbae@uw.edu
description: This website was built using GitHub Pages.
twitter_username: heybaebae
github_username:  heybaebae
linkedin_username: ryanbae89

# Build settings
markdown: kramdown
theme: minima
