# basic options
title: Ryan Bae
author: Ryan Bae
email: ryanbae89@gmail.com
description: This website was built using GitHub Pages.
twitter_username: heybaebae
github_username:  ryanbae89
linkedin_username: ryanbae89

# Build settings
markdown: kramdown
theme: minima
